FROM node:24-alpine AS build
WORKDIR /app


COPY package.json ./
COPY shared/package.json shared/package.json
COPY backend/package.json backend/package.json
COPY frontend/package.json frontend/package.json
RUN npm install

COPY . .
RUN npm run build

#======================

FROM node:24-alpine AS final
WORKDIR /app


COPY --from=build /app/node_modules ./node_modules


COPY --from=build /app/shared/package.json shared/package.json
COPY --from=build /app/shared/dist shared/dist


COPY --from=build /app/backend/package.json backend/package.json
COPY --from=build /app/backend/dist backend/dist


COPY --from=build /app/frontend/dist backend/public

EXPOSE 3001

CMD ["node", "backend/dist/server.js"]
